import type { Metadata } from "next";
import TopNav from "./comopnents/TopNav";
import "./globals.css";

export const metadata: Metadata = {
  title: "포트폴리오",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        style={{ backgroundColor: "var(--bg-color)" }}
      >
        <div>{children}</div>
      </body>
    </html>
  );
}
