import type { Metadata } from "next";
import TopNav from "./comopnents/TopNav";
import "./globals.css";
import { Nanum_Myeongjo } from "next/font/google";

const nanumMyeongjo = Nanum_Myeongjo({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "포트폴리오",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${nanumMyeongjo.className}`}
        style={{ backgroundColor: "var(--bg-color)" }}
      >
        <div>{children}</div>
      </body>
    </html>
  );
}
